### ISSUE TITLE
Name change request from isit:

### ISSUE THREAD

**Issue by ShadedJon** [Aleksey-Terzi/CastleGates#1]
He wants to call the plugin Portcullis

https://en.wikipedia.org/wiki/Portcullis

I'm a fan of the name as it is now, just sending you the feedback

**Comment by Aleksey-Terzi** [comment]
From one side Portcullis is better describing plugin (for those who knows meaning of this word) and also more unique.
From another side I think it is too complicated comparing to CastleGates.
I need to think about this.

EDIT: Oh and also thanks for suggestion

**Comment by Aleksey-Terzi** [comment]
Closing issue since it is not actual anymore
